######################################################################
# Automatically generated by qmake (2.01a) Mo. Nov 21 13:22:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui src/ui
INCLUDEPATH += . src/ui

# Input
HEADERS += src/ui/MainWindow.h
FORMS += ui/main.ui
SOURCES += src/clipcrawler.cpp src/ui/MainWindow.cpp
include(default.pro)
